language: c
compiler: gcc

before_install:
  - sudo apt-get install -y python-pip python-psutil
  - sudo -H pip install lit
addons:
  apt:
    update: true

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make smoketests
  - make tests
